# Header
menu:
  主页: '/'
  #留言: '/MessageBoard/'
  归档: '/archives/'
  # 分类: '/categories/'
  #关于: '/about/'

# SubNav
subnav:
  csdn: 'https://blog.csdn.net/qq_40922859'
  bilibili: 'https://space.bilibili.com/382349038'
  #weibo: "#"
  #zhihu: "#"
  #weixin: '#'
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  github: 'https://github.com/Anyway521'
  #acfun: "#"
  #mail: 'https://cdn.jsdelivr.net/gh/Anyway521/blogpic@main/image/mail.png'
  qq: 'https://cdn.jsdelivr.net/gh/Anyway521/blogpic@main/image/imageMyqq2411535738.jpg'
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  rss: '/atom.xml'

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /
# Content

author: 本该如此

# 文章太长，截断按钮文字，直接在文章里加入<!--more-->就可以注释掉这里
excerpt_link:   
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true
fancybox: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '赏杯Java？٩(๑^o^๑)۶'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
# alipay: '/img/ali.jpg'
# 微信二维码图片地址
# weixin: '/img/weixin.png'
# 自定义打赏码地址
reward_code: '/img/weixin_rp.png'


## 版权声明
copyright: 
    copyright_type: 1      # 0:关闭  1，copyright: true则开启 2，全都开启
    licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/          # 当前应用的版权协议地址。
    licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'  # 版权协议的名称
    licensee_ename: 'CC BY-NC-SA 4.0'                                        #版权协议的英文名称
    licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png      # 版权协议的Logo

# 备案信息，没有请留空
beian: 豫ICP备18033287号-1

# 又拍云开发者计划图片链接，没有请留空
upyun:


# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 标号隐藏：true:隐藏生成目录自带的标号 fasle:不隐藏，默认使用系统带的标号
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

#网站图标，icon格式
favicon: '/img/favicon.ico'

# 头像旋转
rotate: false

# 你的头像url
avatar: 'https://cdn.jsdelivr.net/gh/Anyway521/blogpic@main/image/imageme.jpg'

#是否开启分享，如果不需要建议不要开启
share_jia: true

# Counting words字数统计，看个人需要是否开启
word_count: true
 
# 文章类型，在上面word_count: true的前提下可以进行开启
# 具体类型在对应的md文件开头的 article_type属性进行定义。原创：article_type:0 ，，转载：article_type:1 :
article_type: true


#评论：只保留1.giteement 2.gitalk
#不需要使用某项，直接设置值为false，或注释掉

#1、giteement码云评论系统
giteement:
  enable: true  # 是否启用码云
  redirect_uri: https://anyway521.gitee.io/   # 回调地址
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token  # 授权地址，不能更改
  giteeID: anyway521  # 码云账号英文名
  repo: comment     # 存储评论的 repo
  client_id: '0516788fddee56be44b3b4e8dd8d090500c7dc44e2077ecb1baec5f17a3263db'           #client ID
  client_secret: '48b25a6de68548079c7f237e14346d3f0609aef1626b72d15826b4062b4be430'       #client secret


#2、gitalk
gitalk:
  enable: false #用来做启用判断可以不用
  githubID: Anyway521
  repo: 'comments'
  # 存储博客评论的仓库地址，可以是存储博客的仓库
  ClientID: ''
  ClientSecret: ''
  adminUser: Anyway521
  distractionFreeMode: true

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  # header: '#00BFFF'
  #header: '#00000'
  #开启左侧背景图片切换，需要修改图片请到layout\_partial\left-col.ejs定制
  # bgTab: false
  # 右滑板块背景渐变色
  slider: 'linear-gradient(200deg,#e7eefc,#54c8ff)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# MarkDown文件下载地址,如：http://md.xxwhite.com，以后会写文章教怎么上传原文，不会请留空
mdhost:

# 一言api
hitokoto: true

#pangu.js 用于自动加空格
pangu: true

# 百度统计
baidu_tongji: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章 '
  friends: '友链 '
  aboutme: '关于我'

friends:
  亦往沧劫: 'https://blog.todest.cn/'
  下载本站App: 'https://cdn.jsdelivr.net/gh/Anyway521/Site-app@main/io.anyway521.gitee.apk'

#在这里添加任何配置，都加在“aboutme”的上面，否则会出问题
aboutme: <br>我必须承认<br><br>生命中大部分时光是属于孤独的，<br><br>努力成长<br><br>是在孤独里可以进行的最好的游戏。